/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.collaide.fileuploader.views;

import com.collaide.fileuploader.views.listeners.SingleGroupInfoListener;
import com.collaide.fileuploader.models.user.CurrentUser;
import com.collaide.fileuploader.models.Group;
import com.collaide.fileuploader.models.GroupSync;
import com.collaide.fileuploader.requests.GroupsRequest;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JFileChooser;
import org.apache.log4j.Logger;

/**
 *
 * @author leo
 */
public class GroupPanel extends javax.swing.JPanel {
    private static final Logger logger = Logger.getLogger(GroupPanel.class);

    /**
     * Creates new form GroupPanel
     */
    public GroupPanel() {
        initComponents();
        jlWelcome.setText(jlWelcome.getText() + " " + CurrentUser.getUser().getName());
        Group[] groups = GroupsRequest.index();
        if (groups == null) {
            jlInfo.setText("No groups");
        } else {
            int groupIndex = 0;
            for (Group group : groups) {
                jpGroups.setLayout(new GridBagLayout());
                GridBagConstraints gbc = new GridBagConstraints();
                gbc.gridx = 0;
                gbc.gridy = groupIndex;
                gbc.gridheight = 1;
                gbc.gridwidth = 1;
                SingleGroupInfoPanel groupInfo = new SingleGroupInfoPanel(group);
                groupInfo.addSingleGroupInfoListener(new SingleGroupInfoListener() {

                    @Override
                    public void modifyClicked(SingleGroupInfoPanel panel) {
                        Group groupClicked = panel.getGroup();
                        GroupSync gs = CurrentUser.getUser().getGroupSynchronized(groupClicked.getId());
                        String path = "";
                        if (gs != null) {
                            path = gs.getPath();
                        }
                        if(gs == null) {
                            gs = new GroupSync();
                            gs.setGroup(groupClicked);
                        }
                        if (path == null || path.equals("")) {
                            path = System.getProperty("user.home");
                        }
                        JFileChooser jf = new JFileChooser(path);
                        jf.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                        jf.setAcceptAllFileFilterUsed(false);
                        if (jf.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
                            String selectedpath = jf.getSelectedFile().getAbsolutePath();
                            if (selectedpath != null && !selectedpath.equals("")) {
                                gs.setPath(selectedpath);
                                gs.synchronize();
                                gs.stopObserving();
                                gs.startObserving();
                                CurrentUser.getUser().getGroupSyncList().addGroupSync(gs);
                                panel.setSynchronizedMessage();
                                logger.debug("Synchronized " + gs.getPath());
                            }
                        }
                    }
                });
                jpGroups.add(groupInfo, gbc);

                groupIndex++;
            }
            jlInfo.setText("");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgRepositories = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jlInfo = new javax.swing.JLabel();
        jlWelcome = new javax.swing.JLabel();
        jpGroups = new javax.swing.JPanel();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Select one of your repository to synchronize");

        jlInfo.setText("Pleas wait during your repositories are loading");

        jlWelcome.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jlWelcome.setText("Welcome");

        javax.swing.GroupLayout jpGroupsLayout = new javax.swing.GroupLayout(jpGroups);
        jpGroups.setLayout(jpGroupsLayout);
        jpGroupsLayout.setHorizontalGroup(
            jpGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );
        jpGroupsLayout.setVerticalGroup(
            jpGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jlInfo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jlWelcome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpGroups, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jlWelcome)
                .addGap(18, 18, 18)
                .addComponent(jlInfo)
                .addGap(18, 18, 18)
                .addComponent(jpGroups, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgRepositories;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlInfo;
    private javax.swing.JLabel jlWelcome;
    private javax.swing.JPanel jpGroups;
    // End of variables declaration//GEN-END:variables
}
